---
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 24h
  url: https://democratic-csi.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
      interval: 12h
  values: {}