---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs
  namespace: nfs
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs
      interval: 12h
  values:
    nfs.server: 192.168.1.245
    nfs.path: /data/nfs
    storageClass.name: nfs
    namespace: nfs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-slow
  namespace: nfs
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs
      interval: 12h
  values:
    nfs.server: 192.168.1.245
    nfs.path: /data/nfs-slow
    storageClass.name: nfs-slow
    namespace: nfs

# ---
# apiVersion: helm.cattle.io/v1
# kind: HelmChart
# metadata:
#   name: nfs
#   namespace: nfs
# spec:
#   chart: nfs-subdir-external-provisioner
#   repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
#   targetNamespace: nfs
#   set:
#     nfs.server: 192.168.1.245
#     nfs.path: /data/nfs
#     storageClass.name: nfs
#     namespace: nfs
# ---
# apiVersion: helm.cattle.io/v1
# kind: HelmChart
# metadata:
#   name: nfs-slow
#   namespace: nfs
# spec:
#   chart: nfs-subdir-external-provisioner
#   repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
#   targetNamespace: nfs
#   set:
#     nfs.server: 192.168.1.245
#     nfs.path: /data/nfs-slow
#     storageClass.name: nfs-slow
#     namespace: nfs
