---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-operator
  namespace: prometheus
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: prometheus
spec:
  targetNamespace: prometheus
  interval: 30m
  chart:
    spec:
      chart: prometheus-community/kube-prometheus-stack
      version: "68.4.3"
      sourceRef:
        kind: HelmRepository
        name: prometheus-operator
        namespace: prometheus
      interval: 12h
