apiVersion: v1
kind: Namespace
metadata:
  name: istio-config
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: generic-gateway
  namespace: istio-config
spec:
  selector:
    app: generic-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
